## 异常
异常是程序在执行期间产生的问题。C++ 异常是指在程序运行时发生的特殊情况，比如尝试除以零的操作。    
异常提供了一种转移程序控制权的方式。C++ 异常处理涉及到三个关键字：try、catch、throw。    
> throw: 当问题出现时，程序会抛出一个异常。这是通过使用 throw 关键字来完成的。   
> catch: 在您想要处理问题的地方，通过异常处理程序捕获异常。catch 关键字用于捕获异常。   
> try: try 块中的代码标识将被激活的特定异常。它后面通常跟着一个或多个 catch 块。     

如果 try 块在不同的情境下会抛出不同的异常，这个时候可以尝试罗列多个 catch 语句，用于捕获不同类型的异常。   
### 抛出异常  
可以使用 throw 语句在代码块中的任何地方抛出异常。throw 语句的操作数可以是任意的表达式，表达式的结果的类型决定了抛出的异常的类型。   
```c
//任何地方   
if(b==0)//任何条件   
{   
	throw "Exception"; 	//任何表达式     
}    
```   
### 捕获异常
catch 块跟在 try 块后面，用于捕获异常。    
可以指定想要捕捉的异常类型，这是由 catch 关键字后的括号内的异常声明决定的。   
```c
try   
{   
   // 某个地方throw出来      
}catch( ExceptionName e )   
{    
  // 处理 ExceptionName 异常的代码    
}     
```    
上面的代码会捕获一个类型为ExceptionName的异常。   
如果想让catch块能够处理try块抛出的任何类型的异常，则必须在异常声明的括号内使用省略号...，如下：  
```c
try   
{  
   // 保护代码   
}catch(...)   
{    
  // 能处理任何异常的代码   
}   
```   
### 实例
下面是一个实例，抛出一个除以零的异常，并在 catch 块中捕获该异常。   
```c  
#include <iostream>   
using namespace std;  
 
double division(int a, int b)   
{   
   if( b == 0 )   
   {   
      throw "Division by zero condition!";   
   }   
   return (a/b);   
}   
 
int main ()   
{   
   int x = 50;   
   int y = 0;  
   double z = 0;   
 
   try {   
     z = division(x, y);   
     cout << z << endl;   
   }catch (const char* msg) {    
     cerr << msg << endl;   
   }  
   
   return 0;    
}   
```
由于我们抛出了一个类型为 const char* 的异常，因此，当捕获该异常时，我们必须在 catch 块中使用 const char*。   
### throw()
有时候能看到函数后面跟着一个throw()，这是函数提供者告诉编译器，该函数不抛出任何异常。   
如果一个标明throw()的函数内部发生了throw，编译器会指出，如果没有发现，一旦运行到这里，程序会中止。   
这是异常规范，只出现在声明函数中：   
```c
void GetTag() throw(int);//表示只会抛出int类型异常   
void GetTag() throw(int, char);//表示会抛出int，char类型异常  
void GetTag() throw();//表示不会抛出任何异常   
void GetTag() throw(...);//表示会抛出任何类型异常    
```
需要注意的是，表示只抛出某个类型的异常，并不代表它一定会抛出异常。      
### C++标准的异常
C++ 提供了一系列标准的异常，定义在 <exception> 中，我们可以在程序中使用这些标准的异常。它们是以父子类层次结构组织起来的，如下所示：    
![](https://github.com/sii2017/image/blob/master/cpp_exceptions.jpg)   
下表是对上面层次结构中出现的每个异常的说明：    
![](https://github.com/sii2017/image/blob/master/%E5%BC%82%E5%B8%B8%E8%AF%B4%E6%98%8E.jpg)   
### 定义自己的异常
可以通过继承和重载 exception 类来定义新的异常。该类有个what函数，可以打印异常对象的异常信息。该what函数是虚函数，我们需要继承exception类并重写该what函数，在捕捉异常的时候，我们用父类的引用来接收自定义的标准异常类的子类对象（类型兼容性原则），然后打印该异常信息即可。     
```c
#include <iostream>   
#include <exception>  
using namespace std;    
 
struct MyException : public exception    
{   
  const char * what () const throw ()//throw()说明这个函数中绝不抛出异常，显然他本身就是一个异常（类）      
  {   
    return "C++ Exception";    
  }   
};  
    
int main()   
{  
  try  
  {   
    throw MyException();   
  }    
  catch(MyException& e)   
  {    
    std::cout << "MyException caught" << std::endl;   
    std::cout << e.what() << std::endl;  
  }   
  catch(std::exception& e)   
  {  
    //其他的错误   
  }   
}   
```    
what() 是异常类提供的一个公共方法，它已被所有子异常类重载。   